// @ts-nocheck -- skip type checking
import * as docs_7 from "../content/docs/contributing/testing.mdx?collection=docs&hash=1759373246523"
import * as docs_6 from "../content/docs/contributing/index.mdx?collection=docs&hash=1759373246523"
import * as docs_5 from "../content/docs/contributing/code-of-conduct.mdx?collection=docs&hash=1759373246523"
import * as docs_4 from "../content/docs/getting-started/installation.mdx?collection=docs&hash=1759373246523"
import * as docs_3 from "../content/docs/getting-started/index.mdx?collection=docs&hash=1759373246523"
import * as docs_2 from "../content/docs/meilisearch.mdx?collection=docs&hash=1759373246523"
import * as docs_1 from "../content/docs/index.mdx?collection=docs&hash=1759373246523"
import * as docs_0 from "../content/docs/about.mdx?collection=docs&hash=1759373246523"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"about.mdx","fullPath":"content\\docs\\about.mdx"}, data: docs_0 }, { info: {"path":"index.mdx","fullPath":"content\\docs\\index.mdx"}, data: docs_1 }, { info: {"path":"meilisearch.mdx","fullPath":"content\\docs\\meilisearch.mdx"}, data: docs_2 }, { info: {"path":"getting-started/index.mdx","fullPath":"content\\docs\\getting-started\\index.mdx"}, data: docs_3 }, { info: {"path":"getting-started/installation.mdx","fullPath":"content\\docs\\getting-started\\installation.mdx"}, data: docs_4 }, { info: {"path":"contributing/code-of-conduct.mdx","fullPath":"content\\docs\\contributing\\code-of-conduct.mdx"}, data: docs_5 }, { info: {"path":"contributing/index.mdx","fullPath":"content\\docs\\contributing\\index.mdx"}, data: docs_6 }, { info: {"path":"contributing/testing.mdx","fullPath":"content\\docs\\contributing\\testing.mdx"}, data: docs_7 }], [{"info":{"path":"meta.json","fullPath":"content\\docs\\meta.json"},"data":{"pages":["about","getting-started","meilisearch","contributing"]}}, {"info":{"path":"contributing/meta.json","fullPath":"content\\docs\\contributing\\meta.json"},"data":{"title":"Contributing","pages":["index","testing","code-of-conduct"]}}, {"info":{"path":"getting-started/meta.json","fullPath":"content\\docs\\getting-started\\meta.json"},"data":{"title":"Getting Started","pages":["index","installation"]}}])